version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - auth-service
      - product-service
      - order-service
      - payment-service
      - rabbitmq

  # 認證服務
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthService;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - sqlserver
      - rabbitmq

  # 商品服務
  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=ProductService
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - mongodb
      - rabbitmq

  # 訂單服務
  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=OrderService;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - sqlserver
      - rabbitmq

  # 支付服務
  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PaymentService;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - sqlserver
      - rabbitmq

  # SQL Server 數據庫
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  # MongoDB 數據庫
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # RabbitMQ 消息隊列
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ 服務端口
      - "15672:15672" # RabbitMQ 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  sqlserver_data:
  mongodb_data:
  rabbitmq_data: